# Generated by Django 3.2.9 on 2021-11-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_name', models.CharField(max_length=100)),
                ('Github_link', models.URLField(max_length=500)),
                ('Project_image', models.FileField(max_length=10, upload_to=None)),
            ],
        ),
    ]
