# Generated by Django 3.2.9 on 2021-11-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_name', models.CharField(max_length=100)),
                ('Github_link', models.URLField(max_length=500)),
                ('Project_image', models.ImageField(upload_to='static/images')),
            ],
        ),
        migrations.DeleteModel(
            name='Add_project',
        ),
    ]
