# Generated by Django 3.2.9 on 2021-11-13 10:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_notes_bca_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bca_notes',
            name='unit_notes',
            field=models.FileField(default=django.utils.timezone.now, upload_to=None),
            preserve_default=False,
        ),
    ]
