# Generated by Django 3.2.9 on 2021-12-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_bca_notes_unit_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='bca_sem1_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50)),
                ('UNIT', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50)),
                ('UNIT_name', models.CharField(max_length=150)),
                ('unit_notes', models.FileField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='bca_sem2_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50)),
                ('UNIT', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50)),
                ('UNIT_name', models.CharField(max_length=150)),
                ('unit_notes', models.FileField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='bca_sem3_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50)),
                ('UNIT', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50)),
                ('UNIT_name', models.CharField(max_length=150)),
                ('unit_notes', models.FileField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='bca_sem4_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50)),
                ('UNIT', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50)),
                ('UNIT_name', models.CharField(max_length=150)),
                ('unit_notes', models.FileField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='bca_sem5_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50)),
                ('UNIT', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50)),
                ('UNIT_name', models.CharField(max_length=150)),
                ('unit_notes', models.FileField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='bca_sem6_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50)),
                ('UNIT', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50)),
                ('UNIT_name', models.CharField(max_length=150)),
                ('unit_notes', models.FileField(upload_to=None)),
            ],
        ),
        migrations.DeleteModel(
            name='bca_notes',
        ),
    ]
