# Generated by Django 3.2.9 on 2021-12-25 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20211225_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bca_sem1_notes',
            name='unit_notes',
        ),
        migrations.AddField(
            model_name='bca_sem1_notes',
            name='Drive_link',
            field=models.URLField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
    ]
