# Generated by Django 3.2.9 on 2021-12-25 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20211225_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bca_sem2_notes',
            name='unit_notes',
        ),
        migrations.RemoveField(
            model_name='bca_sem3_notes',
            name='unit_notes',
        ),
        migrations.RemoveField(
            model_name='bca_sem4_notes',
            name='unit_notes',
        ),
        migrations.RemoveField(
            model_name='bca_sem6_notes',
            name='unit_notes',
        ),
        migrations.AddField(
            model_name='bca_sem2_notes',
            name='Drive_link',
            field=models.URLField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bca_sem3_notes',
            name='Drive_link',
            field=models.URLField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bca_sem4_notes',
            name='Drive_link',
            field=models.URLField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bca_sem6_notes',
            name='Drive_link',
            field=models.URLField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
    ]
