# Generated by Django 3.2.9 on 2021-12-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20211225_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='btech_sem1_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50)),
                ('UNIT', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50)),
                ('UNIT_name', models.CharField(max_length=150)),
                ('Drive_link', models.URLField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='btech_sem2_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50)),
                ('UNIT', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50)),
                ('UNIT_name', models.CharField(max_length=150)),
                ('Drive_link', models.URLField(max_length=2000)),
            ],
        ),
    ]
