# Generated by Django 3.2.9 on 2021-12-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_btech_sem1_notes_btech_sem2_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='btech_ce_sem3_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50)),
                ('UNIT', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50)),
                ('UNIT_name', models.CharField(max_length=150)),
                ('Drive_link', models.URLField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='btech_ce_sem4_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50)),
                ('UNIT', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50)),
                ('UNIT_name', models.CharField(max_length=150)),
                ('Drive_link', models.URLField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='btech_ce_sem5_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50)),
                ('UNIT', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50)),
                ('UNIT_name', models.CharField(max_length=150)),
                ('Drive_link', models.URLField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='btech_ce_sem6_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50)),
                ('UNIT', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50)),
                ('UNIT_name', models.CharField(max_length=150)),
                ('Drive_link', models.URLField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='btech_ce_sem7_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50)),
                ('UNIT', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50)),
                ('UNIT_name', models.CharField(max_length=150)),
                ('Drive_link', models.URLField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='btech_ce_sem8_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50)),
                ('UNIT', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50)),
                ('UNIT_name', models.CharField(max_length=150)),
                ('Drive_link', models.URLField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='btech_cs_sem3_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50)),
                ('UNIT', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50)),
                ('UNIT_name', models.CharField(max_length=150)),
                ('Drive_link', models.URLField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='btech_cs_sem4_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50)),
                ('UNIT', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50)),
                ('UNIT_name', models.CharField(max_length=150)),
                ('Drive_link', models.URLField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='btech_cs_sem5_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50)),
                ('UNIT', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50)),
                ('UNIT_name', models.CharField(max_length=150)),
                ('Drive_link', models.URLField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='btech_cs_sem6_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50)),
                ('UNIT', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50)),
                ('UNIT_name', models.CharField(max_length=150)),
                ('Drive_link', models.URLField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='btech_cs_sem7_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50)),
                ('UNIT', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50)),
                ('UNIT_name', models.CharField(max_length=150)),
                ('Drive_link', models.URLField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='btech_cs_sem8_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50)),
                ('UNIT', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50)),
                ('UNIT_name', models.CharField(max_length=150)),
                ('Drive_link', models.URLField(max_length=2000)),
            ],
        ),
    ]
