# Generated by Django 3.1.14 on 2022-01-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_auto_20220126_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='mba_sem1_notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50)),
                ('UNIT', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50)),
                ('UNIT_name', models.CharField(max_length=150)),
                ('Drive_link', models.URLField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='mba_sem2_notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50)),
                ('UNIT', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50)),
                ('UNIT_name', models.CharField(max_length=150)),
                ('Drive_link', models.URLField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='mba_sem3_notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50)),
                ('UNIT', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50)),
                ('UNIT_name', models.CharField(max_length=150)),
                ('Drive_link', models.URLField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='mba_sem4_notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50)),
                ('UNIT', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50)),
                ('UNIT_name', models.CharField(max_length=150)),
                ('Drive_link', models.URLField(max_length=2000)),
            ],
        ),
    ]
