# Generated by Django 3.2.8 on 2021-11-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211108_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='about',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
