# Generated by Django 3.2.8 on 2021-11-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_notice_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='notice',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='about',
            new_name='title',
        ),
    ]
