# Generated by Django 3.2.8 on 2021-11-09 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211108_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='detail',
            new_name='notice',
        ),
    ]
