# Generated by Django 3.2.8 on 2021-11-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_detail_notice_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='testing1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anshul', models.CharField(max_length=50)),
            ],
        ),
    ]
