# Generated by Django 3.2.8 on 2021-11-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_testing1'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing1',
            name='link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
