# Generated by Django 3.2.8 on 2021-11-09 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_testing1_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testing1',
        ),
    ]
