# Generated by Django 3.2.8 on 2021-11-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete_testing1'),
    ]

    operations = [
        migrations.CreateModel(
            name='notice1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=2000)),
            ],
        ),
    ]
