# Generated by Django 3.2.8 on 2021-11-10 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='event',
            new_name='event1',
        ),
    ]
