# Generated by Django 3.2.8 on 2021-11-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_event_event1'),
    ]

    operations = [
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(verbose_name='1')),
                ('last_date', models.DateField()),
                ('quiz_name', models.CharField(max_length=150)),
                ('quiz_link', models.URLField()),
            ],
        ),
    ]
