# Generated by Django 3.2.8 on 2021-11-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='serial',
            field=models.IntegerField(verbose_name=models.AutoField(primary_key=True, verbose_name='1')),
        ),
    ]
