# Generated by Django 3.2.8 on 2021-11-12 06:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_quiz_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
