# Generated by Django 3.2.8 on 2021-11-12 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_quiz_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='quiz',
        ),
    ]
