# Generated by Django 3.2.8 on 2021-11-12 07:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
