# Generated by Django 3.2.8 on 2021-11-12 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_quiz_serial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='time',
            new_name='time1',
        ),
    ]
