# Generated by Django 3.2.8 on 2021-11-12 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_rename_time_quiz_time1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='time1',
        ),
    ]
