# Generated by Django 3.2.9 on 2021-11-12 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='time',
        ),
    ]
