# Generated by Django 3.2.9 on 2021-11-14 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='event1',
            new_name='event',
        ),
    ]
