# Generated by Django 3.2.9 on 2021-11-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_rename_event1_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='event1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('event_date', models.DateField()),
                ('event_link', models.URLField()),
            ],
        ),
    ]
