# Generated by Django 3.2.9 on 2021-11-21 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_event1'),
    ]

    operations = [
        migrations.AddField(
            model_name='event1',
            name='poster',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/event_posters'),
            preserve_default=False,
        ),
    ]
