# Generated by Django 3.2.9 on 2021-11-21 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_event1_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='event1',
            name='details',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
