# Generated by Django 3.2.9 on 2021-12-26 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20211226_1323'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='event',
            new_name='events1',
        ),
    ]
