# Generated by Django 3.2.9 on 2021-12-26 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_rename_event_events1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='events1',
            new_name='Allevents',
        ),
    ]
