# Generated by Django 3.2.9 on 2021-12-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_rename_events1_allevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('event_date', models.DateField()),
                ('event_link', models.URLField()),
                ('details', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Allevents',
        ),
    ]
